# See https://docs.rubocop.org/rubocop/configuration
plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - '**/*_test.rb'
Metrics/AbcSize:
  Exclude:
    - '**/*_test.rb'
Minitest/MultipleAssertions:
  Exclude:
    - '**/*_test.rb'
