name: Update Dependencies
on:
  push:
  schedule:
    - cron: "0 0 1 * *"
permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: make

      - name: update gem
        run: |
          bundle config unset deployment
          bundle update
          bundle exec -- rubocop -A
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Update dependencies"
          title: "Update dependencies"
          branch: "update-dependencies"
          delete-branch: true
          reviewers: takkyuuplayer
