name: Update Dependencies
on: [push, pull_request]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: make

      - name: update gem
        run: |
          bundle config unset deployment
          bundle update
          bundle exec -- rubocop -A
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          commit-message: "Update dependencies"
          title: "Update dependencies"
          branch: "update-dependencies"
          delete-branch: true
          reviewers: takkyuuplayer
          body: |
            Run

            ```
            $ git fetch --all
            $ git checkout update-dependencies
            $ git reset --hard origin/update-dependencies
            $ git commit --allow-empty -m "run ci"
            $ git push
            ```
